import { Prisma } from '@/generated/prisma'
import { createResourceConfig } from '@/common/utils/create-resource-config'

export const orderSettlementsResourceConfig = createResourceConfig<
  Prisma.OrderSettlementScalarFieldEnum,
  Prisma.OrderSettlementWhereInput
>({
  allowedSortBy: [
    'id',
    'orderId',
    'kind',
    'status',
    'currency',
    'amount',
    'dueAt',
    'paidAt',
    'createdAt',
    'updatedAt',
  ],
  allowedSelect: [
    'id',
    'orderId',
    'kind',
    'status',
    'payerUserId',
    'payeeUserId',
    'beneficiaryUserId',
    'toCounterpartyId',
    'toAccountId',
    'fromAccountId',
    'method',
    'currency',
    'amount',
    'note',
    'dueAt',
    'paidAt',
    'createdAt',
    'updatedAt',
  ],
  defaultSelect: [
    'id',
    'orderId',
    'kind',
    'status',
    'payerUserId',
    'payeeUserId',
    'beneficiaryUserId',
    'toCounterpartyId',
    'toAccountId',
    'fromAccountId',
    'method',
    'currency',
    'amount',
    'note',
    'dueAt',
    'paidAt',
    'createdAt',
    'updatedAt',
  ],
  enforcedSelect: ['id'],
  defaultSortBy: 'createdAt',
  defaultSortOrder: 'desc',
  tieBreakerField: 'id',
  tieBreakerOrder: 'asc',
})
