import { Prisma } from '@/generated/prisma'
import { createResourceConfig } from '@/common/utils/create-resource-config'

export const transactionsResourceConfig = createResourceConfig<
  Prisma.TransactionScalarFieldEnum,
  Prisma.TransactionWhereInput
>({
  allowedSortBy: [
    'id',
    'type',
    'method',
    'ownerUserId',
    'initiatorUserId',
    'currency',
    'amount',
    'occurredAt',
    'createdAt',
    'updatedAt',
  ],
  allowedSelect: [
    'id',
    'type',
    'method',
    'ownerUserId',
    'initiatorUserId',
    'fromUserId',
    'toUserId',
    'beneficiaryUserId',
    'fromAccountId',
    'toAccountId',
    'fromCounterpartyId',
    'toCounterpartyId',
    'amount',
    'currency',
    'referenceCode',
    'note',
    'occurredAt',
    'createdAt',
    'updatedAt',
  ],
  defaultSelect: [
    'id',
    'type',
    'method',
    'ownerUserId',
    'initiatorUserId',
    'fromUserId',
    'toUserId',
    'beneficiaryUserId',
    'fromAccountId',
    'toAccountId',
    'fromCounterpartyId',
    'toCounterpartyId',
    'amount',
    'currency',
    'referenceCode',
    'note',
    'occurredAt',
    'createdAt',
    'updatedAt',
  ],
  enforcedSelect: ['id'],
  defaultSortBy: 'occurredAt',
  defaultSortOrder: 'desc',
  tieBreakerField: 'id',
  tieBreakerOrder: 'asc',
})
