import { Prisma } from '@/generated/prisma'
import { createResourceConfig } from '@/common/utils/create-resource-config'

export const saleExecutionsResourceConfig = createResourceConfig<
  Prisma.SaleExecutionScalarFieldEnum,
  Prisma.SaleExecutionWhereInput
>({
  allowedSortBy: [
    'id',
    'assetCurrency',
    'quantitySold',
    'proceedsCurrency',
    'proceedsAmount',
    'netProceedsAmount',
    'costBasisMethod',
    'costBasisCurrency',
    'costBasisAmount',
    'realizedProfitAmount',
    'occurredAt',
    'createdAt',
    'updatedAt',
  ],
  allowedSelect: [
    'id',
    'ownerUserId',
    'counterpartyId',
    'settlementAccountId',
    'assetCurrency',
    'quantitySold',
    'feeCurrency',
    'feeAmount',
    'consumedQuantity',
    'proceedsCurrency',
    'proceedsAmount',
    'netProceedsAmount',
    'unitSalePrice',
    'costBasisMethod',
    'costBasisCurrency',
    'costBasisAmount',
    'realizedProfitAmount',
    'occurredAt',
    'note',
    'createdAt',
    'updatedAt',
  ],
  defaultSelect: [
    'id',
    'ownerUserId',
    'counterpartyId',
    'settlementAccountId',
    'assetCurrency',
    'quantitySold',
    'feeCurrency',
    'feeAmount',
    'consumedQuantity',
    'proceedsCurrency',
    'proceedsAmount',
    'netProceedsAmount',
    'unitSalePrice',
    'costBasisMethod',
    'costBasisCurrency',
    'costBasisAmount',
    'realizedProfitAmount',
    'occurredAt',
    'note',
    'createdAt',
    'updatedAt',
  ],
  enforcedSelect: ['id'],
  defaultSortBy: 'occurredAt',
  defaultSortOrder: 'desc',
  tieBreakerField: 'id',
  tieBreakerOrder: 'asc',
})
